spring.application.name=enterprise-resource-planning

#database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ERPDB
spring.datasource.username=postgres
spring.datasource.password=admin

#jpa setup
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update


##Mail Code by gpt
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
